tasks:
  - init: cd ./execompte-web
    command: npm install
    command: npm install -g @angular/cli
    command: ng serve
    command: 'echo "execompte-web initialized"'
  - init: cd ./execompte-api
    command: mvn clean install -Dmaven.test.skip=true
    command: 'echo "execompte-api initialized"'
    command: mvn spring-boot:run