image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addLabel: prebuild-in-gitpod
tasks:
  - init: |
      cd ./execompte-web
      npm install
    command: |
      cd ./execompte-api
      npm install -g @angular/cli
      ng analytics off
      ng serve --proxy-config proxy.config.json --host 0.0.0.0 --disable-host-check --port 4200
  - init: |
      cd ./execompte-api
      mvn clean install -Dmaven.test.skip=true
      /workspace/ExeCompte/setup.sh
      gp sync-done SETUP
  - command: |
      gp sync-await SETUP
      mkdir -p /workspace/data
      mongod --auth --port 27017 --dbpath /workspace/data
  - command: |
      gp await-port 27017
      cd ./execompte-api      
      mvn spring-boot:run
ports:
  - port: 27017
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 4200
    onOpen: open-browser