image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addLabel: prebuild-in-gitpod
tasks:
  - init: |
      cd ./execompte-web
      npm install
    command: |
      cd ./execompte-web
      npm install -g @angular/cli
      ng analytics off
      export PRODUCTION=false; export API_URL=$(gp url 4200); export PLATFORM=GITPOD_DEV; export PORT=4200; npm start
  - init: |
      cd ./execompte-api
      mvn clean install -Dmaven.test.skip=true
      /workspace/ExeCompte/startMongoDbOn27015.sh  
  - command: |
      gp await-port 27015
      /workspace/ExeCompte/createMongoDbUser.sh
      gp sync-done MONGO_STOP_AFTER_USER_CREATION
  - command: |
      gp sync-await MONGO_STOP_AFTER_USER_CREATION
      mongod --auth --port 27017 --dbpath /workspace/data
  - command: |
      gp await-port 27017
      cd ./execompte-api
      mvn spring-boot:run -Dspring-boot.run.arguments=--client.url=$(gp url 4200)
ports:
  - port: 27017
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 4200
    onOpen: open-browser
