tasks:
  - init: |
      cd ./execompte-web
      npm install
    command: >
      npm install -g @angular/cli &&
      ng serve &&
      'echo "execompte-web initialized"'
  - init: |
      cd ./execompte-api
      mvn clean install -Dmaven.test.skip=true
    command: >
      'echo "execompte-api initialized"' &&
      mvn spring-boot:run