tasks:
  - init: |
      cd ./execompte-web
      npm install
    command: >
      npm install -g @angular/cli &&
      ng serve
  - init: |
      cd ./execompte-api
      mvn clean install -Dmaven.test.skip=true
    command: >
      mvn spring-boot:run